config/routes.rb
Rails.application.routes.draw do
  get 'static_pagesrake/routes'

  root 'static_pages#home'

  devise_for :users
  resources  :users

  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  scope :by_post_and_user, -> (post_id, user_id) { where(post_id: post_id, user_id: user_id) }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  scope :draft, -> { where(status: 'draft') }
  scope :posted, -> { where(status: 'posted') }

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.by_post_and_user(params[:post_id], current_user.id)
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
    else
    end
  end

  def destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:post_id, :description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :init_post, only: [:update, :edit, :destroy]
  after_action :update_user_statistic, only: [:create, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc).includes(:comments)
  end

  def new
    @post = Post.new
    @posts = current_user.posts
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new', status: 303
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to :back
  end

  private

    def init_post
      @post = current_user.posts.find(params[:id])
    end

    def update_user_statistic
      return unless @post.errors.blank?
      current_user.update_attribute(:posts_count, current_user.posts.length)
    end

    def post_params
      params.require(:post).permit(:title, :content, :status)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @user = User.first
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class='post'>
  <div class='title' >
    <%= @post.title %>
    <label class='created-at'> <%= @post.created_at.strftime('%d-%m-%y') %> </label>
  </div>
  <div class='content-description'> <%= @post.content %> </div>
</div>

<div class='comments-list'>
  <% @comments.each do |comment| %>
    <div class='comment'>
      <%= comment.description %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnGit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">All users</a></li>
            <li><%= link_to 'Posts', posts_path %></li>
            <% unless current_user.nil? %>
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li><%= link_to 'Create new post', new_post_path %> </li>
            <% end %>
          </ul>
        </li>
        <% if current_user.nil? %>
          <li><%= link_to 'sign in', new_user_session_path %></li>
          <li><%= link_to 'sign up', new_user_registration_path %></li>
        <% else %>
          <li><%= current_user.posts_count %></li>
          <li><%= link_to 'logout', destroy_user_session_path, method: 'DELETE' %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class='warpper'>
  <%= yield %>
</div>
<div class='footer'>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class='create-new-post'>
  <% unless post.errors.blank? %>
    <div> Some shit was happen </div>
    <ul class='errors'>
      <% post.errors.each do |key, value| %>
        <li class='error-message'><%= key %> <%= value %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for post, method: method do |t| %>
    <div class='input-group'>
      <label> title </label>
      <%= t.text_field :title, class: 'form-control'  %>
    </div>
    <div class='input-group'>
      <label> content </label>
      <%= t.text_field :content, class: 'form-control'  %>
    </div>
    <div class='input-group'>
      <%= t.submit %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='post'>
  <div class='title' >
    <%= post.title %>
    <% if current_user.id == post.user_id %>
      <label> <%= link_to 'edit', edit_post_path(post.id) %> </label>
      <label> <%= link_to 'view comments', post_comments_path(post.id) %> </label>
      <label> <%= link_to 'delete', post_path(post.id), method: :delete %> </label>
      <label class='created-at'> <%= post.created_at.strftime('%d-%m-%y') %> </label>
    <% end %>
  </div>
  <div class='content-description'> <%= post.content %> </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: 'form', locals: { post: @post, method: :put } %>

app/views/posts/index.html.erb
<div class='posts-list'>
  <% @posts.each do |post| %>
    <%= render partial: 'post', locals: { post: post } %>
    <% post.comments.each do |comment| %>
      <%=  %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: 'form', locals: { post: @post, method: :post } %>

<div class='posts-list'>
  <% @posts.each do |post| %>
    <%= render partial: 'post', locals: { post: post } %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h2>Your profile</h2>
<%= form_for @user do |f| %>

  <div class="new-user">
    <%= f.label :email %><br/>
    <%= f.email_field :email %><br />
  </div>

  <div class="new-user">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %><br />
  </div>

  <div class="new-user">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %><br />
  </div>

  <div class="new-user">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="new-user">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="new-user">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>